matrix:
  include:
    - os: osx
      osx_image: xcode11
script:
  - swift package generate-xcodeproj
  - xcodebuild -project Mockingjay.xcodeproj -scheme Mockingjay-Package -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' test
  - pod lib lint --quick
